### ISSUE TITLE
Create a diamond patern with canvas

### ISSUE THREAD

**Issue by pat51100** [dzaima/Canvas#4]
Hi.
I want to create this pattern with canvas

    *
   * *
  *   *
 *     *
*       *
 *     *
  *   *
   * *
    *
I try to enter 
****／╬
But i have got this wrong pattern (i have got two stars at the top instead of one)
And twice  lines in the middle of the pattern
Can you help me please ?

    **    
   *  *   
  *    *  
 *      * 
*        *
*        *
 *      * 
  *    *  
   *  *   
    **

**Comment by pat51100** [comment]
![diamond](https://github.com/dzaima/Canvas/assets/153749902/69081148-29e0-4ff3-9862-304f2600918d)
At right the good pattern
At left, the pattern i get by enter ****／╬

**Comment by dzaima** [comment]
You'd want `****／┼`

**Comment by pat51100** [comment]
Thanks a lot ;)
