### ISSUE TITLE
repeat a pattern vertically and horizontally with the right connection

### ISSUE THREAD

**Issue by pat51100** [dzaima/Canvas#6]
Hi.
By enter
 oooo／┼２＊
i got twice the pattern (vertically), but i want it to be connected only by one circle (see the picture)
How can i modify few of the code to make it work ?
![pat2](https://github.com/dzaima/Canvas/assets/153749902/63060025-8a7e-4062-a6a0-d4883264ab10)

I've got the same problem horizontally with this code 
oooo／┼２×
i got twice the pattern (horizontally), but i want it to be connected only by one circle (see the picture)
How can i modify few of the code to make it work ?
![pat1](https://github.com/dzaima/Canvas/assets/153749902/359bf7f5-5859-47ec-a095-58137119dd5f)
Thanks for any help :)

**Comment by dzaima** [comment]
For two times exactly here, you can `oooo／┼─` for horizontal, `oooo／┼│` for vertical, or `oooo／┼∙┼` for both.

For an arbitrary size, there's `oooo／┼Ｊ；３＊∔`, and probably with some `⤢` for horizontal.

**Comment by pat51100** [comment]
Thank you very much.
I understand and it works for two times exactly (first line of your previous message) but not for arbitrary size ...
When i enter" oooo／┼Ｊ；３＊∔    ",   i've got only one pattern on the screen.
What do i have to enter if i want 9 pattern (3 horizontally x 3 vertically) ?

**Comment by dzaima** [comment]
`oooo／┼Ｊ；３＊∔⤢Ｊ；３＊∔` is one approach. I never really finished Canvas tbh, there's a bunch of useful features missing.

**Comment by pat51100** [comment]
Thank you
I don't know why but i got only one pattern when i test it and
enter oooo／┼Ｊ；３＊∔⤢Ｊ；３＊∔
What is the problem ?

**Comment by dzaima** [comment]
Works fine for me: [link](https://dzaima.github.io/Canvas/?u=b29vbyV1RkYwRiV1MjUzQyV1RkYyQSV1RkYxQiV1RkYxMyV1RkYwQSV1MjIxNCV1MjkyMiV1RkYyQSV1RkYxQiV1RkYxMyV1RkYwQSV1MjIxNA__,v=8)

**Comment by pat51100** [comment]
Thank you very much and bravo ;)
Is there a mail address where i can contact you ?
